### ISSUE TITLE
Include items from shared Google Drive folders

### ISSUE THREAD

**Issue by mtakemoto** [Cleod9/syncmarx-webext#26]
I'm trying to get this extension to work with my team, but it doesn't seem like the API request to Google Drive pulls shared folders by default.  It would be nice to include them since that would open up sharing bookmarks across a group of people.

This seems like a relatively simple fix with 2 query string parameters added: `includeItemsFromAllDrives=true&supportsAllDrives=true`.  (see https://developers.google.com/drive/api/v3/reference/files/list?apix_params=%7B%22corpora%22%3A%22user%22%2C%22includeItemsFromAllDrives%22%3Atrue%2C%22supportsAllDrives%22%3Atrue%7D)

I've been trying to get builds set up on Windows but `node-sass` keeps giving me issues.  And Firefox also refused to launch...what OS are you developing on?

I'll try to make a PR eventually after I spin up a Linux VM, but I wanted to run this by you first.  Some issues I see are having both local and shared folders named `syncmarx`.  

Another solution this could be to have the user specify the folder ID in the URL (`https://drive.google.com/drive/folders/{copy-this-part}`), but that would require a UI change.

Anyway, thank you for making this thing!

**Comment by Cleod9** [comment]
Sorry for the slow response, but thanks for the report and details! I hope to make some updates to this repo soon-ish since recent api changes have been problematic on both Google Drive and Dropbox causing the extension to fall apart. It's just been incredibly busy for me lately so I haven't gotten around to it yet. I develop in Windows 10 by the way, but it's possible a specific older version of Node.js may be needed at this point in time, so some packages may need to be updated as well.

Anyway, it seems like it shouldn't be too bad of a fix based on your notes but I'm not sure when I'd be able to get to it just yet. I did eventually want to add more advanced features in terms of sync source and destination which would actually clear up a lot of these sorts of issues, just need the time to do it 😅

**Comment by Cleod9** [comment]
@mtakemoto Better late than never, I've updated the extension with `includeItemsFromAllDrives=true&supportsAllDrives=true`. Closing for now, but can be re-opened if there is an issue
